#!/usr/bin/env python

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import time
import numpy as np
import pandas as pd
import math
import os
import logging
import gzip
import glob

from Bio import SeqIO

#global logging
logging.basicConfig(filename = 'window_func.log', 
                    level=logging.INFO, 
                    filemode='w', 
                    format='%(asctime)s - %(levelname)s - %(message)s')

logger = logging.getLogger()

def make_windows(genome, win, slide, chrom, animal, df):
    n_names = [col for col in df.columns if col.startswith('N')]
    logger.info("n_names: %s", n_names)

    x_names = [col for col in df.columns if col.startswith('X')]
    logger.info("x_names: %s", x_names)

    n_pos = df.shape[0]
    n_ani = len(n_names)

    a = np.zeros((n_pos, n_ani))
    for i in range(n_ani):
        a[:,i] = df[x_names[i]].values/df[n_names[i]].values

    ## convert NaN to 0
    a = np.nan_to_num(a)
    logger.info("a.shape: %s", a.shape)

    pos = df["Pos"]
    site_end = int(pos.max())


## sliding windows for single animal
    ani_dict={}
    for j, n in enumerate(n_names):
        ani_dict[n]=j
    i_a=ani_dict[animal]
    logger.debug('Animal id: %s, animal index %s', animal, i_a)
    start_time = time.time()


#impute zeros to empty sites
    y = np.zeros(site_end) # +1 because from 0 to df[:,0].max()
    for i,j in enumerate(pos):
        y[int(j)-1] = a[i,i_a]
# find where the zeros end
    site_start = int(pos.min())

# calculate window_mean
    n_windows = math.ceil((len(y[site_start:]) - win)/slide) + 1
    window_mean = np.zeros(n_windows)
    window_seq = np.empty(n_windows, dtype='S200') #max length window possible is 200
    window_beg = np.zeros(n_windows)
    window_end = np.zeros(n_windows)
    i = 0 #initiate indexing for window_mean
    p = site_start-1 #because python uses 0 indexing
    record_dict = SeqIO.index(genome,'fasta')
    record = record_dict[chrom]
    while i < n_windows:
        w_mean = y[p:p+win].mean()
        window_mean[i]=w_mean
        window_beg[i]=p
        window_end[i]=window_beg[i]+win
        window_seq[i]=str(record.seq[int(window_beg[i]):int(window_end[i])])
        p += slide
        i+=1 
    print("finished -- ia: {}, time: {:.2f}".format(animal, time.time() - start_time))
    ta=np.array(list(zip(window_beg+1,window_end+1,window_mean,window_seq)), 'd,d,f,U200')
    return ta


def get_chroms(outfile, genome, win, slide, stress,chrom,animal):
    path = '/datasets/work/af-mlai-bio/work/Heat_Stress_Use-case/Data_for_Tai/'
    if chrom=='all':
        file_list = glob.glob(path + 'filtered_meth_HE{}_chrm*.dat'.format(stress))
        df_list = [pd.read_csv(file, sep="\s+") for file in file_list]
    else:
        file_list = glob.glob(path + 'filtered_meth_HE{}_chrm{}.dat'.format(stress, chrom))
     
    for file in file_list:
        chrom = file.split('chrm')[1].split('.')[0]
        print(chrom)
        df = pd.read_csv(file, sep='\s+')
        ta = make_windows(genome, win, slide, chrom, animal, df)
        with open(outfile,'a') as out:
            np.savetxt(out, ta, fmt="%d %d %.3f %s")
    

def get_out_file_name(stress, chrom, animal, win, slide):  
    return "window_mean_HE%s_chrm%s_ia%s_win%s_step%s.txt"%(stress, chrom, animal, win, slide)

#unused for now
def fasta_slider(seq_record, size, step):
    """generates sliding windows over nucleotide sequence"""
    i = 0
    while (i < len(seq_record.seq)) :
        f_out = (str(seq_record.seq[i:i+size]) + "\n")
        i += step
    
def main(args):
    """Main logic of program."""
    genome = args.genome
    win = args.win
    slide = args.slide
    stress = args.HE
    chrom = args.chrom
    animal = args.an

    out_file = get_out_file_name(stress, chrom, animal, win, slide)

    get_chroms(out_file, genome, win, slide, stress, chrom, animal)
    
if __name__ == "__main__":

    import argparse


    #parse command line arguments
    parser = argparse.ArgumentParser(description='Generates tab-delimited tidy\
        data for sliding windows over methylation input files generated by Andrew.')
                                     
    #positional arguments
    parser.add_argument('genome', help='Input fasta genome file')
    parser.add_argument('win', help='Sliding window size', type=int)
    parser.add_argument('slide', help='Sliding window step', type=int)
    parser.add_argument("HE", help="Heat stress stage, one of [1,2,3]")
    parser.add_argument("chrom", help="Chromosome id, from 1 to 29",\
        default='all', type=str)
    parser.add_argument("an", help="Animal id, one of NX where X is the identifier",\
        default='all', type=str)

    args = parser.parse_args()
    #run program
    main(args)
